const Groq = require("groq-sdk")
const puppeteer = require("puppeteer")

const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY
})

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {
  const prompt = `You are an expert interview coach. Generate an interview report as a JSON object.

Job Description: ${jobDescription}
Resume: ${resume || "Not provided"}
Self Description: ${selfDescription || "Not provided"}

Return ONLY a JSON object with exactly these fields:
{
  "title": "job title string",
  "matchScore": number between 0-100,
  "atsScore": number between 0-100,
  "atsSummary": "short summary of how well the resume/self description is optimized for ATS parsing and the job description",
  "matchedKeywords": ["keyword string"],
  "missingKeywords": ["keyword string"],
  "atsSuggestions": ["specific resume improvement suggestion"],
  "technicalQuestions": [
    {
      "question": "question string",
      "intention": "intention string",
      "answer": "answer string"
    }
  ],
  "behavioralQuestions": [
    {
      "question": "question string",
      "intention": "intention string",
      "answer": "answer string"
    }
  ],
  "skillGaps": [
    {
      "skill": "skill string",
      "severity": "low" or "medium" or "high"
    }
  ],
  "preparationPlan": [
    {
      "day": 1,
      "focus": "focus string",
      "tasks": ["task1", "task2"]
    }
  ]
}

Generate an ATS score by comparing the resume/self description against the job description, including keyword coverage, relevant experience, measurable impact, formatting clarity, and role alignment.
Generate at least 8 matched keywords, 8 missing keywords, 5 ATS suggestions, 20 technical questions, 20 behavioral questions, 3 skill gaps and a 7 day preparation plan.
Return ONLY the JSON object, no extra text.`

  const response = await groq.chat.completions.create({
    model: "llama-3.3-70b-versatile",
    messages: [
      {
        role: "user",
        content: prompt
      }
    ],
    response_format: { type: "json_object" },
    temperature: 0.7,
  })

  return JSON.parse(response.choices[0].message.content)
}

async function generatePdfFromHtml(htmlContent) {
  const browser = await puppeteer.launch({
    args: ["--no-sandbox", "--disable-setuid-sandbox"]
  })
  const page = await browser.newPage()
  await page.setContent(htmlContent, { waitUntil: "networkidle0" })

  const pdfBuffer = await page.pdf({
    format: "A4",
    margin: {
      top: "20mm",
      bottom: "20mm",
      left: "15mm",
      right: "15mm"
    }
  })

  await browser.close()
  return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {
  const prompt = `You are an expert resume writer. Generate a professional resume in HTML format.

Job Description: ${jobDescription}
Resume: ${resume || "Not provided"}
Self Description: ${selfDescription || "Not provided"}

Return ONLY a JSON object with exactly this field:
{
  "html": "complete HTML content of the resume"
}

The resume should be:
- Tailored for the given job description
- Well formatted and visually appealing with simple professional styling
- ATS friendly
- Ideally 1-2 pages when converted to PDF
- Not sound like it is generated by AI

Return ONLY the JSON object, no extra text.`

  const response = await groq.chat.completions.create({
    model: "llama-3.3-70b-versatile",
    messages: [
      {
        role: "user",
        content: prompt
      }
    ],
    response_format: { type: "json_object" },
    temperature: 0.7,
  })

  const jsonContent = JSON.parse(response.choices[0].message.content)
  const pdfBuffer = await generatePdfFromHtml(jsonContent.html)
  return pdfBuffer
}

async function evaluateMockInterviewAnswer({
  jobDescription,
  resume,
  selfDescription,
  question,
  intention,
  modelAnswer,
  userAnswer,
  questionType
}) {
  const prompt = `You are a senior interviewer and interview coach. Evaluate the candidate's mock interview answer as a JSON object.

Question Type: ${questionType}
Job Description: ${jobDescription}
Resume: ${resume || "Not provided"}
Self Description: ${selfDescription || "Not provided"}
Interview Question: ${question}
Question Intention: ${intention}
Reference Answer: ${modelAnswer}
Candidate Answer: ${userAnswer}

Return ONLY a JSON object with exactly these fields:
{
  "overallScore": number between 0-100,
  "clarityScore": number between 0-100,
  "relevanceScore": number between 0-100,
  "depthScore": number between 0-100,
  "summary": "2 sentence coaching summary",
  "strengths": ["specific strength"],
  "improvements": ["specific improvement"],
  "improvedAnswer": "a stronger version of the candidate answer in first person",
  "followUpQuestion": "one realistic interviewer follow-up question"
}

Score the answer against the job description, the intention behind the question, and the expected answer quality. Keep feedback practical and interview-ready.
Return ONLY the JSON object, no extra text.`

  const response = await groq.chat.completions.create({
    model: "llama-3.3-70b-versatile",
    messages: [
      {
        role: "user",
        content: prompt
      }
    ],
    response_format: { type: "json_object" },
    temperature: 0.4,
  })

  return JSON.parse(response.choices[0].message.content)
}

async function evaluateMockInterview({ jobDescription, resume, selfDescription, responses }) {
  const formattedResponses = responses.map((response, index) => `
Question ${index + 1} (${response.questionType}):
${response.question}

Question intention: ${response.intention}
Reference answer: ${response.modelAnswer}
Candidate answer: ${response.userAnswer}`).join("\n")

  const prompt = `You are a senior hiring manager. Evaluate this complete mock interview only after considering every answer.

Job Description: ${jobDescription}
Resume: ${resume || "Not provided"}
Self Description: ${selfDescription || "Not provided"}

Interview transcript:
${formattedResponses}

Return ONLY a JSON object with exactly these fields:
{
  "finalScore": number between 0-100,
  "verdict": "Strong Hire" or "Hire" or "Borderline" or "Not Ready",
  "technicalScore": number between 0-100,
  "behavioralScore": number between 0-100,
  "communicationScore": number between 0-100,
  "summary": "a concise 2-3 sentence final assessment",
  "strengths": ["specific strength demonstrated across the interview"],
  "improvements": ["specific improvement supported by the candidate's answers"],
  "nextSteps": ["practical preparation action"],
  "questionFeedback": [
    {
      "questionNumber": 1,
      "score": number between 0-100,
      "feedback": "one concise sentence"
    }
  ]
}

Include one questionFeedback item for every interview response, in the same order. Base the final score and verdict on the full interview, role alignment, accuracy, relevance, depth, clarity, and evidence. Do not invent experience that the candidate did not mention.
Return ONLY the JSON object, no extra text.`

  const response = await groq.chat.completions.create({
    model: "llama-3.3-70b-versatile",
    messages: [
      {
        role: "user",
        content: prompt
      }
    ],
    response_format: { type: "json_object" },
    temperature: 0.3,
  })

  return JSON.parse(response.choices[0].message.content)
}

module.exports = {
  generateInterviewReport,
  generateResumePdf,
  evaluateMockInterviewAnswer,
  evaluateMockInterview
}
